export const ADD_NEW_TIMER = 'ADD_NEW_TIMER';
export const TOGGLE_TIMER = 'TOGGLE_TIMER';
export const ADD_TOTAL_TIMER= 'ADD_TOTAL_TIMER';
export const ADD_NEW_TIMER_SHOW='ADD_NEW_TIMER_SHOW';
export const UPDATE_TIMER_SHOW='UPDATE_TIMER_SHOW';